# volumes:
#   node_modules:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./client:/src
      - /src/node_modules
