apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/greenhouseproject-default: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: jamaica
            - name: POSTGRES_USER
              value: postgres
          image: markbruderer/greenhousedb
          name: database
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
