apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: humidity
  name: humidity
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: humidity
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/greenhouseproject-default: "true"
        io.kompose.service: humidity
    spec:
      containers:
        - image: markbruderer/humidity
          name: humidity
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
