apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: messagequeue
  name: messagequeue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: messagequeue
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/greenhouseproject-default: "true"
        io.kompose.service: messagequeue
    spec:
      containers:
        - image: apache/activemq-classic
          name: messagequeue
      restartPolicy: Always
