apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: messagequeue
  name: messagequeue
spec:
  ports:
    - name: "61614"
      port: 61614
      targetPort: 61614
    - name: "61616"
      port: 61616
      targetPort: 61616
  selector:
    io.kompose.service: messagequeue
