apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: temperature
  name: temperature
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: temperature
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/greenhouseproject-default: "true"
        io.kompose.service: temperature
    spec:
      containers:
        - image: markbruderer/temperature
          name: temperature
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
