apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ventilation
  name: ventilation
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: ventilation
