apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: device-manager
  name: device-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: device-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: device-manager
    spec:
      containers:
        - image: device-manager
          name: device-manager
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
