apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: greenhouse
  name: greenhouse
spec:
  containers:
    - image: greenhouse
      name: greenhouse
      ports:
        - containerPort: 8080
      resources: {}
  restartPolicy: OnFailure
status: {}
