apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: irrigation
  name: irrigation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: irrigation
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: irrigation
    spec:
      containers:
        - image: irrigation
          name: irrigation
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
