apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: temperature
  name: temperature
spec:
  containers:
    - image: temperature
      name: temperature
      ports:
        - containerPort: 8081
      resources: {}
  restartPolicy: OnFailure
status: {}
